import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./../globals.css";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { toastDefaultOptions } from "@/components/ui/toast/toast";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function Layout({children}: Readonly<{ children: React.ReactNode;}>) {
    return (
        <html className="min-h-dvh h-full bg-base-100" data-theme="valanticDark">
            <body className="h-full">
                {children}
                <ToastContainer {...toastDefaultOptions} />
            </body>
        </html>
    );
}
