import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./../globals.css";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { toastDefaultOptions } from "@/components/ui/toast/toast";
import Navbar from "@/components/ui/nav/navbar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{ children: React.ReactNode;}>) {
    return (
        <html className="min-h-dvh h-full bg-base-100" data-theme="valanticDark">
            <body className="h-full">
                <Navbar />
                <main className="mt-20 p-8 md:p-4 max-w-7xl w-full mx-auto">
                    {children}
                </main>
                <ToastContainer {...toastDefaultOptions} />
            </body>
        </html>
    );
}
