import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{ children: React.ReactNode;}>) {
    return (
        <html className="min-h-dvh h-full bg-base-100">
            <body className="h-full">
                {children}
            </body>
        </html>
    );
}
